{{- $dot := . }}
{{- range $secret := .Values.secrets -}}
{{ $data := dict "dot" $dot "module" $secret }}
{{- if not (lookup "v1" "Secret" $dot.Release.Namespace $secret.name) }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $secret.name }}
  labels:
    {{- include "getLabels" $data | trim  | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
data:
  {{- range $key := $secret.keys }}
  {{ $key }}:
  {{- end }}
{{- end }}
{{- end }}
