# Configuration of ConfigMaps
configMaps: []

# Configuration of Secrets
secrets: []

# Configuration of ImagePullSecrets
imagePullSecrets: []

# Configuration of Modules
modules: []

global:
  subchart1:
    enabled: true
