{{/*
Creates a OpenShift Route resource if enabled in values.
*/}}
{{- define "common.route" -}}
{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    {{- with .Values.route.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  host: {{ .Values.route.host | quote }}
  {{- if .Values.route.path }}
  path: {{ .Values.route.path | quote }}
  {{- end }}
  wildcardPolicy: {{ .Values.route.wildcardPolicy | quote }}
  port:
    targetPort: {{ .Values.service.port }}
{{- if .Values.route.tls }}
  tls:
{{- with .Values.route.tls }}
    termination: {{ .termination }}
    insecureEdgeTerminationPolicy: {{ .insecureEdgeTerminationPolicy }}
    {{- with .key }}
    key: |
{{ . | indent 6 }}
    {{- end }}
    {{- with .certificate }}
    certificate: |
{{ . | indent 6 }}
    {{- end }}
    {{- with .caCertificate }}
    caCertificate: |
{{ . | nindent 6 }}
    {{- end }}
    {{- with .destinationCACertificate }}
    destinationCACertificate: |
{{ . | nindent 6 }}
    {{- end }}
{{- end }}
{{- end }}
  to:
    kind: Service
    name: {{ include "common.fullname" . }}
{{- end }}
{{- end -}}
