{{/* 
Create a Service

Usage:
{{ include "common.service" . }}

Params:
  - .Values.service.type       - String     - Optional. The type of service to create (ClusterIP, NodePort, LoadBalancer, etc.), defaults to ClusterIP.
  - .Values.service.port       - Int        - Required. The port the service should serve on.
  - .Values.service.name       - String     - Optional. The name of the service port, defaults to "http".
  - .Values.service.targetPort - Int|String - Optional. Container port or port name; defaults to .Values.service.port.
*/}}
{{- define "common.service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ required "service.port is required" .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.name | default "http" }}
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
---
{{- end -}}