apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  {{- with .Values }}
  application.yml: |
    de.muenchen.oss.ad2image:
      {{- if .defaultMode }}
      default-mode: {{ .defaultMode | quote }}
      {{- end }}
      ad:
        url: {{ required "AD url must be provided" .ad.url | quote }}
        user-search-base: {{ required "AD user-search-base must be provided" .ad.userSearchBase | quote }}
        user-search-filter: {{ required "AD user-search-filter must be provided" .ad.userSearchFilter | quote }}
      ews:
        ews-service-url: {{ required "EWS service url must be provided" .ews.ewsServiceUrl | quote }}
      gravatar:
        enabled: {{ .gravatar.enabled | quote }}
        hash-cache-refresh-cron: {{ .gravatar.hashCacheRefreshCron | quote }}
        map-population-filter: {{ .gravatar.mapPopulationFilter | quote }}
        page-size: {{ .gravatar.pageSize | quote }}
        {{- if .gravatar.defaultMode }}
        default-mode: {{ .gravatar.defaultMode | quote }}
        {{- end }}
      web.docs.url: {{ .docsUrl | default "/swagger-ui/index.html" | quote }}

    logging:
      level:
        "[de.muenchen.oss.ad2image]": INFO
  {{- end }}
