{{- if (not .Values.credentials.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}
  labels: 
    {{- include "common.labels" . | nindent 4 }}
data:
  {{- with .Values.credentials }}
  AD_USER_DN: {{ required "AD user-dn must be provided" .adUserDn | b64enc | quote }}
  AD_PASSWORD: {{ required "AD password must be provided" .adPassword | b64enc | quote }}
  EWS_PASSWORD: {{ required "EWS password must be provided" .ewsPassword | b64enc | quote }}
  EWS_USERNAME: {{ required "EWS username must be provided" .ewsUsername | b64enc | quote }}
  {{- end }}
{{- end }}
