{{- if (not .Values.credentials.existingSecret) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
stringData:
  {{- with .Values.credentials }}
  AD_USER_DN: {{ required "AD user-dn must be provided" .adUserDn | quote }}
  AD_PASSWORD: {{ required "AD password must be provided" .adPassword | quote }}
  EWS_PASSWORD: {{ required "EWS password must be provided" .ewsPassword | quote }}
  EWS_USERNAME: {{ required "EWS username must be provided" .ewsUsername | quote }}
  {{- end }}
{{- end }}
