apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "appswitcher-server-helm-chart.fullname" . }}
  labels:
    {{- include "appswitcher-server-helm-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "appswitcher-server-helm-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if (not .Values.credentials.existingSecret) }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "appswitcher-server-helm-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "appswitcher-server-helm-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: config
          configMap:
            {{- if .Values.existingConfigMap }}
            name: {{ .Values.existingConfigMap }}
            {{- else }}
            name: {{ include "appswitcher-server-helm-chart.fullname" . }}
            {{- end }}
            defaultMode: 420
      {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- with .Values.initContainers }}
        {{- toYaml . | nindent 8}}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- if .Values.activeSpringProfiles }}
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.activeSpringProfiles | quote }}
          {{- end}}
          {{- with .Values.extraEnvVars }}
            {{- toYaml . | nindent 12 }}
          {{- end}}
          {{- if contains "keycloak" .Values.activeSpringProfiles }}
          envFrom:
            - prefix: APPSWITCHER_KEYCLOAK_
              secretRef:
                {{- if .Values.credentials.existingSecret }}
                name: {{ .Values.credentials.existingSecret }}
                {{- else }}
                name: {{ include "appswitcher-server-helm-chart.fullname" . }}
                {{- end }}
          {{- end}}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /workspace/config
          {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 60
            timeoutSeconds: 15
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
