{{- if and (not .Values.credentials.existingSecret) (contains "keycloak" .Values.activeSpringProfiles ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
stringData:
  {{- with .Values.credentials }}
  CLIENT_ID: {{ required "Client ID must be provided" .clientId | quote }}
  CLIENT_SECRET: {{ required "Client secret must be provided" .clientSecret | quote }}
  {{- end }}
{{- end }}
