{{- if and (not .Values.credentials.existingSecret) (contains "keycloak" .Values.activeSpringProfiles ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "appswitcher-server-helm-chart.fullname" . }}
  labels: 
    {{- include "appswitcher-server-helm-chart.labels" . | nindent 4 }}
data:
  {{- with .Values.credentials }}
  CLIENT_ID: {{ required "Client ID must be provided" .clientId | b64enc | quote }}
  CLIENT_SECRET: {{ required "Client secret must be provided" .clientSecret | b64enc | quote }}
  {{- end }}
{{- end }}
