kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "zammad-ldap-sync.name" . }}
  labels:
    {{- include "zammad-ldap-sync.labels" . | nindent 4 }}
data:
   {{- with .Values.ldapSync.applicationYML }}
  application.yaml: |
    {{- toYaml . | nindent 4 }}
  {{- end }}