apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "zammad-ldap-sync.name" . }}
  labels:
    {{- include "zammad-ldap-sync.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.ldapSync.cronjob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: zammad-ldap-sync
            image: "{{ .Values.ldapSync.image.registry }}/{{ .Values.ldapSync.image.repository }}:{{ .Values.ldapSync.image.tag }}"
            imagePullPolicy: {{ .Values.ldapSync.image.pullPolicy }}
            envFrom:
            - secretRef:
                name: {{ .Values.ldapSync.cronjob.secret }}
            volumeMounts:
              ## truststore
              - mountPath: /etc/pki/ca-trust/extracted/java
                name: cacerts-lhm
                readOnly: true
              - name: properties-volume
                subPath: application.yaml
                mountPath: /deployments/application.yaml
          volumes:
            ## truststore
            - name: cacerts-lhm
              secret:
                defaultMode: 420
                secretName: cacerts-lhm
                items:
                  - key: cacerts-lhm
                    path: cacerts
            - name: properties-volume
              configMap:
                name: {{ include "zammad-ldap-sync.name" . }}
                items:
                  - key: application.yaml
                    path: application.yaml
          restartPolicy: OnFailure
