{{- $dot := . }}
{{- range $module := .Values.modules -}}
{{ $data := dict "dot" $dot "module" $module }}
{{- if $module.autoscaling }}
{{- if or $module.autoscaling.targetCPUUtilizationPercentage $module.autoscaling.targetMemoryUtilizationPercentage }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "getFullname" $data }}
  labels:
    {{- include "getLabels" $data | trim | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $module.name }}
  minReplicas: {{ $module.autoscaling.minReplicas | default 1 }}
  maxReplicas: {{ $module.autoscaling.maxReplicas }}
  metrics:
    {{- if $module.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $module.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $module.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $module.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
