apiVersion: v2
name: pentaho-carte
description: Pentaho Data Integration installation and starts the Pentaho Carte Server
type: application
# Chart version.
version: 0.1.4
# Pentaho Dataintegration version
appVersion: "0.0.2"
maintainers:
  - name: ejcsid
    email: ejcsid@gmail.com
home: https://github.com/it-at-m/helm-charts/tree/main/charts/pentaho-carte
icon: https://raw.githubusercontent.com/it-at-m/helm-charts/main/images/logo.png
sources:
  - "https://github.com/it-at-m/helm-charts"
