apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ezldap.fullname" . }}
  labels: 
    {{- include "ezldap.labels" . | nindent 4 }}
data:
  {{- with .Values.applicationYML }}
  application.yml: |
    {{- toYaml . | nindent 4 }}
  {{- end }}
