{{- if .Values.eaiRoute.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "ezldap.fullname" . }}-eai
  labels:
    {{- include "ezldap.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.eaiRoute.whitelist }}
    haproxy.router.openshift.io/ip_whitelist: {{ .Values.eaiRoute.whitelist | quote }}
  {{- end }}
  {{- with .Values.eaiRoute.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  host: {{ .Values.eaiRoute.host | quote }}
  path: {{ .Values.eaiRoute.path }}
  wildcardPolicy: {{ .Values.eaiRoute.wildcardPolicy }}
  port:
    targetPort: {{ .Values.service.port }}
{{- if .Values.eaiRoute.tls }}
  tls:
{{- with .Values.eaiRoute.tls }}
    termination: {{ .termination }}
    insecureEdgeTerminationPolicy: {{ .insecureEdgeTerminationPolicy }}
    {{- with .key }}
    key: |
{{ . | indent 6 }}
    {{- end }}
    {{- with .certificate }}
    certificate: |
{{ . | indent 6 }}
    {{- end }}
    {{- with .caCertificate }}
    caCertificate: |
{{ . | nindent 6 }}
    {{- end }}
    {{- with .destinationCACertificate }}
    destinationCACertificate: |
{{ . | nindent 6 }}
    {{- end }}
{{- end }}
{{- end }}
  to:
    kind: Service
    name: {{ include "ezldap.fullname" . }}
{{- end }}
