{{- if (not .Values.credentials.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}
  labels: 
    {{- include "common.labels" . | nindent 4 }}
data:
  {{- with .Values.credentials }}
  USER_DN: {{ required "LDAP user-dn must be provided" .userDn | b64enc | quote }}
  PASSWORD: {{ required "LDAP password must be provided" .password | b64enc | quote }}
  {{- end }}
{{- end }}
