apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  {{- with .Values.applicationYml }}
  application.yml: |-
    {{- tpl . $ | nindent 4 }}
  {{- end }}
