apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "java-spring-boot.fullname" . }}
  labels:
    {{- include "java-spring-boot.labels" . | nindent 4 }}
data:
  {{- with .Values.applicationYml }}
  application.yml: |-
    {{- toYaml . | nindent 4 }}
  {{- end }}
