{{- if .Values.build.enabled }}
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: {{ required "build.outputImageStreamName must be configured" .Values.build.outputImageStreamName }}
  labels: {{- include "common.labels" . | nindent 4 }}
{{- end }}
