{{- $credentials := .Values.credentials }}
{{- range $name, $credential := $credentials }}
{{- if not $credential.existingSecret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "java-spring-boot.secretName" (dict "defaultNameSuffix" $name "context" $) }}
  labels:
    {{- include "java-spring-boot.labels" $ | nindent 4 }}
  {{- with $credential.keepSecret }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
data:
  {{- range $key, $value := $credential.data }}
  {{ $key }}: {{ printf "%v" $value | b64enc | quote }}
  {{- end }}
---
{{- end }}
{{- end }}
