{{- if and .Values.hazelcast.assignRoleToServiceAccount .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hazelcast-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hazelcast-role
subjects:
  - kind: ServiceAccount
    name: {{ include "refarch-gateway.serviceAccountName" . }}
{{- end }}