# Default specific values for dave.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# Dave Backend
backend:
  # Environment Variables
  extraEnvVars:
    env:
      JAVA_OPTIONS: -Djavax.net.ssl.trustStore=/mnt/cacerts -Djavax.net.ssl.trustStorePassword=changeit
        -Xmx1g --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED
        --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED
        --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED
        --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED"
    # Dave Email Settings
    email:
      DAVE_EMAIL_RECEIVER_HOSTNAME: imap.example.com
      DAVE_EMAIL_ADDRESS: dave-dev@example.com
      DAVE_EMAIL_RECEIVER_CUT_EMAIL_BODY_LINE_CONTAINS_STRINGS: Example City;-----Ursprüngliche Nachricht-----;dave-dev@example.com,
  # Credentials
  credentials:
    DAVE_EMAIL_PASSWORD: WFhYWC1TRUNSRVQtWFhYWAo=
  # Volume for CA-Certfificates
  # extraVolumeMounts:
  #   - name: cacerts
  #     readOnly: true
  #     mountPath: /mnt
  # extraVolumes:
  #   - name: cacerts
  #     secret:
  #       secretName: cacerts
  #       defaultMode: 420

# Dave Admin-Portal
admin-portal:
  # Environment variables
  extraEnvVars:
    JAVA_OPTIONS: -Djavax.net.ssl.trustStore=/mnt/cacerts -Djavax.net.ssl.trustStorePassword=changeit
      --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens
      java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens
      java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED
      --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
  # Volume for CA-Certfificates
  # extraVolumeMounts:
  #   - name: cacerts
  #     readOnly: true
  #     mountPath: /mnt
  # extraVolumes:
  #   - name: cacerts
  #     secret:
  #       secretName: cacerts
  #       defaultMode: 420
  ingress:
    enabled: true
    className: ""
    hosts:
      - host: dave-admin-portal.example.de
        paths:
          - path: /
            pathType: ImplementationSpecific

# Dave EAI
eai:
  # Environment variables
  extraEnvVars:
    JAVA_OPTIONS: -Djavax.net.ssl.trustStore=/mnt/cacerts -Djavax.net.ssl.trustStorePassword=changeit -Xmx512m
  # Volume for CA-Certfificates
  # extraVolumeMounts:
  #   - name: cacerts
  #     readOnly: true
  #     mountPath: /mnt
  # extraVolumes:
  #   - name: cacerts
  #     secret:
  #       secretName: cacerts
  #       defaultMode: 420


# Dave Frontend
frontend:
  # Environment variables
  extraEnvVars:
    JAVA_OPTIONS: -Djavax.net.ssl.trustStore=/mnt/cacerts -Djavax.net.ssl.trustStorePassword=changeit
      --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens
      java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens
      java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED
      --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
  # Volume for CA-Certfificates
  # extraVolumeMounts:
  #   - name: cacerts
  #     readOnly: true
  #     mountPath: /mnt
  # extraVolumes:
  #   - name: cacerts
  #     secret:
  #       secretName: cacerts
  #       defaultMode: 420
  ingress:
    enabled: true
    className: ""
    hosts:
      - host: dave.example.de
        paths:
          - path: /
            pathType: ImplementationSpecific


# Dave Selfservice-Portal
selfservice-portal:
  # Environment variables
  extraEnvVars:
    JAVA_OPTIONS: -Djavax.net.ssl.trustStore=/mnt/cacerts -Djavax.net.ssl.trustStorePassword=changeit
      --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens
      java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens
      java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED
      --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
  # Volume for CA-Certfificates
  # extraVolumeMounts:
  #   - name: cacerts
  #     readOnly: true
  #     mountPath: /mnt
  # extraVolumes:
  #   - name: cacerts
  #     secret:
  #       secretName: cacerts
  #       defaultMode: 420
  ingress:
    enabled: true
    className: ""
    hosts:
      - host: dave-selfservice-portal.example.de
        paths:
          - path: /
            pathType: ImplementationSpecific
