# Default specific values for dave.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global values
global:
  credentials:
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT-SECRET: WFhYWC1TRUNSRVQtWFhYWAo=
  extraEnvVars:
    - name: SPRING_SECURITY_LOGGING_REQUESTS
      value: "all"

# Dave Backend
backend:
  existingSecret: ""                # verhindert Fehler durch fehlendes Secret
  service:
    ports:
      - port: 8080
        targetPort: 8080
        protocol: TCP
        name: service
  hazelcast:
    enabled: false
  # Environment Variables
  extraEnvVars:
    JAVA_OPTIONS:
      -Djavax.net.ssl.trustStore=/mnt/cacerts -Djavax.net.ssl.trustStorePassword=changeit
      -Xmx1g --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED
      --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED
      --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED
      --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED"
    SPRING_PROFILES_ACTIVE: dev,no-security
    SPRING_FLYWAY_ENABLED: "false"
    KEYCLOAK_AUTH-SERVER-URL: http://dave-keycloak
#    ELASTICSEARCH_SCHEME: http
#    ELASTICSEARCH_SECURITY_ENABLED: "false"
#    ELASTICSEARCH_SECURITY_TLS_AUTOGENERATED: "false"
    ELASTICSEARCH_PASSWORD: ""
    ELASTICSEARCH_HOST: ""
    ELASTICSEARCH_USER: ""
    ELASTICSEARCH_PORT: "0"
    ELASTICSEARCH_CONNECTTIMEOUT: "0"
    ELASTICSEARCH_SOCKETTIMEOUT: "0"
    ELASTICSEARCH_HTTPCACERTIFICATE: ""
    SPRING_DATA_ELASTICSEARCH_REPOSITORIES_ENABLED: "false"
#    SPRING_ELASTICSEARCH_URIS: "http://dave-elasticsearch:9200"
    SPRING_ELASTICSEARCH_URIS: ""
    SPRING_DATASOURCE_URL: jdbc:postgresql://dave-postgresql:5432/dave_db
    SPRING_DATASOURCE_USERNAME: dave
    SPRING_DATASOURCE_PASSWORD: dave_pwd
    SPRING_JPA_HIBERNATE_DDLAUTO: none
    HZ_INTEGRITYCHECKER_ENABLED: "false"
    HZ_JET_ENABLED: "false"
    # Dave Email Settings
    DAVE_EMAIL_RECEIVER_HOSTNAME: imap.example.com
    DAVE_EMAIL_SENDER_HOSTNAME: smtp.example.com
    DAVE_EMAIL_ADDRESS: dave-dev@example.com
    DAVE_EMAIL_RECEIVER_CUTEMAILBODY_LINECONTAINSSTRINGS: Example City;-----Ursprüngliche Nachricht-----;dave-dev@example.com,
  # Credentials
    DAVE_EMAIL_PASSWORD: WFhYWC1TRUNSRVQtWFhYWAo=
  # Volume for CA-Certfificates
  # extraVolumeMounts:
  #   - name: cacerts
  #     readOnly: true
  #     mountPath: /mnt
  # extraVolumes:
  #   - name: cacerts
  #     secret:
  #       secretName: cacerts
  #       defaultMode: 420

# Dave Admin-Portal
admin-portal:
  service:
    port: 8080
    ports:
      - port: 8080
        targetPort: 8080
        protocol: TCP
        name: service
  hazelcast:
    enabled: false
  # Environment variables
  extraEnvVars:
    JAVA_OPTIONS:
      -Djavax.net.ssl.trustStore=/mnt/cacerts -Djavax.net.ssl.trustStorePassword=changeit
      --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens
      java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens
      java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED
      --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
    SPRING_PROFILES_ACTIVE: dev,no-security
    SPRING_CLOUD_GATEWAY_ROUTES_0_URI: http://dave-keycloak/
    SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER-URI: http://dave-keycloak/realms/dave
  # Volume for CA-Certfificates
  # extraVolumeMounts:
  #   - name: cacerts
  #     readOnly: true
  #     mountPath: /mnt
  # extraVolumes:
  #   - name: cacerts
  #     secret:
  #       secretName: cacerts
  #       defaultMode: 420
  ingress:
    enabled: true
    className: ""
    hosts:
      - host: dave-admin-portal.example.de
        paths:
          - path: /
            pathType: ImplementationSpecific

# Dave EAI
eai:
  hazelcast:
    enabled: false
  # Environment variables
  extraEnvVars:
    JAVA_OPTIONS: -Djavax.net.ssl.trustStore=/mnt/cacerts -Djavax.net.ssl.trustStorePassword=changeit -Xmx512m
    SPRING_PROFILES_ACTIVE: dev,no-security
  # Volume for CA-Certfificates
  # extraVolumeMounts:
  #   - name: cacerts
  #     readOnly: true
  #     mountPath: /mnt
  # extraVolumes:
  #   - name: cacerts
  #     secret:
  #       secretName: cacerts
  #       defaultMode: 420

# Dave Frontend
frontend:
  service:
    port: 8080
    ports:
      - port: 8080
        targetPort: 8080
        protocol: TCP
        name: service
  hazelcast:
    enabled: false
  # Environment variables
  extraEnvVars:
    JAVA_OPTIONS:
      -Djavax.net.ssl.trustStore=/mnt/cacerts -Djavax.net.ssl.trustStorePassword=changeit
      --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens
      java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens
      java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED
      --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
    SPRING_PROFILES_ACTIVE: dev,no-security
    SPRING_CLOUD_GATEWAY_ROUTES_0_URI: http://dave-keycloak/
    SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER-URI: http://dave-keycloak/realms/dave
  # Volume for CA-Certfificates
  # extraVolumeMounts:
  #   - name: cacerts
  #     readOnly: true
  #     mountPath: /mnt
  # extraVolumes:
  #   - name: cacerts
  #     secret:
  #       secretName: cacerts
  #       defaultMode: 420
  ingress:
    enabled: true
    className: ""
    hosts:
      - host: dave.example.de
        paths:
          - path: /
            pathType: ImplementationSpecific

# Dave Selfservice-Portal
selfservice-portal:
  service:
    port: 8080
    ports:
      - port: 8080
        targetPort: 8080
        protocol: TCP
        name: service
  hazelcast:
    enabled: false
  # Environment variables
  extraEnvVars:
    JAVA_OPTIONS:
      -Djavax.net.ssl.trustStore=/mnt/cacerts -Djavax.net.ssl.trustStorePassword=changeit
      --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens
      java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens
      java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED
      --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
    SPRING_PROFILES_ACTIVE: dev,no-security
    SPRING_CLOUD_GATEWAY_ROUTES_0_URI: http://dave-keycloak/
    SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER-URI: http://dave-keycloak/realms/dave
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT-ID: dave
    HZ_INTEGRITYCHECKER_ENABLED: "false"
    HZ_JET_ENABLED: "false"
    HAZELCAST_ENABLED: "false"
  # Volume for CA-Certfificates
  # extraVolumeMounts:
  #   - name: cacerts
  #     readOnly: true
  #     mountPath: /mnt
  # extraVolumes:
  #   - name: cacerts
  #     secret:
  #       secretName: cacerts
  #       defaultMode: 420
  ingress:
    enabled: true
    className: ""
    hosts:
      - host: dave-selfservice-portal.example.de
        paths:
          - path: /
            pathType: ImplementationSpecific

# Dave Document Storage
document-storage:
  hazelcast:
    enabled: false
  # Environment variables
  extraEnvVars:
    JAVA_OPTIONS: -Djavax.net.ssl.trustStore=/mnt/cacerts -Djavax.net.ssl.trustStorePassword=changeit -Xmx512m
    SPRING_PROFILES_ACTIVE: dev,no-security
    KEYCLOAK_AUTH-SERVER-URL: http://dave-keycloak
    REFARCH_S3_URL: s3.example.com
    REFARCH_S3_BUCKETNAME: dave-bucket
    REFARCH_S3_ACCESSKEY: EXAMPLE
    REFARCH_S3_SECRETKEY: dummysecret
    DE_MUENCHEN_REFARCH_INTEGRATION_S3_ENABLED: "false"
    SPRING_SECURITY_LOGGING_REQUESTS: all

# Dave Geodata Eai
geodata-eai:
  hazelcast:
    enabled: false

# Keycloak
keycloak:
  fullnameOverride: "dave-keycloak"
  keycloakConfigCli:
    annotations:
      # to trigger immediate execution of keycloak-config-ci
      helm.sh/hook: null

# elasticsearch:
#  fullnameOverride: dave-elasticsearch
#  # keine persistent volumes im CI (kind)
#  persistence:
#    enabled: false
#  esConfig:
#    elasticsearch.yml: |
#      xpack.security.enabled: false
#      xpack.security.http.ssl.enabled: false
#      xpack.security.transport.ssl.enabled: false
#      discovery.type: single-node
#  # geringe Ressourcen für CI/kind
#  master:
#    resources:
#      limits:
#        memory: 512Mi
#      requests:
#        memory: 256Mi

postgresql:
  fullnameOverride: dave-postgresql
  primary.persistence.enabled: false
  auth:
    postgresPassword: postgrespw               # Superuser-Passwort (optional)
    username: dave                              # erzeugter DB-User
    password: dave_pwd                      # Passwort für erzeugten User
    database: dave_db                           # erzeugte DB
