# Default specific values for dave.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

externalCharts:
  elasticsearch:
    # enable/disable elasticsearch chart dependency
    enabled: true
  postgresql:
    # enable/disable postgresql chart dependency
    enabled: true
  backend:
    # enable/disable backend chart dependency
    enabled: true
  frontend:
    # enable/disable frontend chart dependency
    enabled: true
  adminportal:
    # enable/disable adminportal chart dependency
    enabled: true
  selfserviceportal:
    # enable/disable selfservice chart dependency
    enabled: true
  eai:
    # enable/disable eai chart dependency
    enabled: true
  documentstorage:
    # enable/disable documentstorage chart dependency
    enabled: true
  geodataeai:
    # enable/disable geodataeai chart dependency
    enabled: true

# Dave Backend
backend:
  # Environment Variables
  extraEnvVars:
    env:
      JAVA_OPTS_APPEND:
        -Djavax.net.ssl.trustStore=/mnt/cacerts -Djavax.net.ssl.trustStorePassword=changeit
        -Xmx1g --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED
        --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED
        --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED
        --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
      SPRING_PROFILES_ACTIVE: dev,no-security
      # Elasticsearch
      ELASTICSEARCH_SECURITY_ENABLED: "false"
      ELASTICSEARCH_SECURITY_TLS_AUTOGENERATED: "false"
      ELASTICSEARCH_SCHEME: http
      ELASTICSEARCH_HTTPCACERTIFICATE: ""
    # Dave Email Settings
    email:
      DAVE_EMAIL_RECEIVER_HOSTNAME: imap.example.com
      DAVE_EMAIL_SENDER_HOSTNAME: smtp.example.com
      DAVE_EMAIL_ADDRESS: dave-dev@example.com
      DAVE_EMAIL_RECEIVER_CUT_EMAIL_BODY_LINE_CONTAINS_STRINGS: Example City;-----Ursprüngliche Nachricht-----;dave-dev@example.com,
  # Credentials
  credentials:
    DAVE_EMAIL_PASSWORD: WFhYWC1TRUNSRVQtWFhYWAo=

# Dave Admin-Portal
admin-portal:
  # Environment variables
  extraEnvVars:
    env:
      JAVA_OPTS_APPEND:
        -Djavax.net.ssl.trustStore=/mnt/cacerts -Djavax.net.ssl.trustStorePassword=changeit
        --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens
        java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens
        java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED
        --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
      SPRING_PROFILES_ACTIVE: dev,no-security
      SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_0_URI: http://dave-keycloak/
  ingress:
    enabled: true
    className: ""
    hosts:
      - host: dave-admin-portal.example.de
        paths:
          - path: /
            pathType: ImplementationSpecific

# Dave EAI
eai:
  # Environment variables
  extraEnvVars:
    env:
      JAVA_OPTS_APPEND: -Djavax.net.ssl.trustStore=/mnt/cacerts -Djavax.net.ssl.trustStorePassword=changeit -Xmx512m
      SPRING_PROFILES_ACTIVE: dev,no-security

# Dave Frontend
frontend:
  # Environment variables
  extraEnvVars:
    env:
      JAVA_OPTS_APPEND:
        -Djavax.net.ssl.trustStore=/mnt/cacerts -Djavax.net.ssl.trustStorePassword=changeit
        --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens
        java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens
        java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED
        --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
      SPRING_PROFILES_ACTIVE: dev,no-security
      SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_0_URI: http://dave-keycloak/
  ingress:
    enabled: true
    className: ""
    hosts:
      - host: dave.example.de
        paths:
          - path: /
            pathType: ImplementationSpecific

# Dave Selfservice-Portal
selfservice-portal:
  # Environment variables
  extraEnvVars:
    env:
      JAVA_OPTS_APPEND:
        -Djavax.net.ssl.trustStore=/mnt/cacerts -Djavax.net.ssl.trustStorePassword=changeit
        --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens
        java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens
        java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED
        --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
      SPRING_PROFILES_ACTIVE: dev,no-security
      SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_0_URI: http://dave-keycloak/
  ingress:
    enabled: true
    className: ""
    hosts:
      - host: dave-selfservice-portal.example.de
        paths:
          - path: /
            pathType: ImplementationSpecific

# Dave Document Storage
document-storage:
  # Environment variables
  extraEnvVars:
    env:
      JAVA_OPTS_APPEND: -Djavax.net.ssl.trustStore=/mnt/cacerts -Djavax.net.ssl.trustStorePassword=changeit -Xmx512m
      SPRING_PROFILES_ACTIVE: dev,no-security
      REFARCH_S3_URL: s3.example.com
      REFARCH_S3_BUCKETNAME: dave-bucket
      REFARCH_S3_ACCESSKEY: EXAMPLE
      REFARCH_S3_SECRETKEY: dummysecret
      DE_MUENCHEN_REFARCH_INTEGRATION_S3_ENABLED: "false"
      SPRING_SECURITY_LOGGING_REQUESTS: all

elasticsearch:
  fullnameOverride: "dave-elasticsearch"
  # keine persistent volumes im CI (kind)
  persistence:
    enabled: false
  esConfig:
    elasticsearch.yml: |
      xpack.security.enabled: false
      xpack.security.http.ssl.enabled: false
      xpack.security.transport.ssl.enabled: false
      discovery.type: single-node
  # geringe Ressourcen für CI/kind
  master:
    heapSize: 512m
    resources:
      limits:
        memory: 1Gi
      requests:
        memory: 512Mi

postgresql:
  fullnameOverride: dave-postgresql
  primary:
    persistence:
      enabled: false
  auth:
    postgresPassword: postgrespw            # Superuser-Passwort (optional)
    username: dave                          # erzeugter DB-User
    password: dave_pwd                      # Passwort für erzeugten User
    database: dave_db                       # erzeugte DB
